CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL ,
	[Email] NVARCHAR(255) NOT NULL,
	[Phone] NVARCHAR(255) NOT NULL,
	[Password] NVARCHAR(255) NOT NULL

)
